#!/bin/sh
set -eu

template_path="/etc/openflashcards/runtime-config.template.js"
output_path="/usr/share/nginx/html/runtime-config.js"

export OPENFLASHCARDS_API_URL="${OPENFLASHCARDS_API_URL:-http://localhost:3030/api/v1}"
export OPENFLASHCARDS_API_TIMEOUT="${OPENFLASHCARDS_API_TIMEOUT:-10000}"
export OPENFLASHCARDS_API_RETRY_ATTEMPTS="${OPENFLASHCARDS_API_RETRY_ATTEMPTS:-3}"
export OPENFLASHCARDS_API_RETRY_DELAY="${OPENFLASHCARDS_API_RETRY_DELAY:-1000}"
export OPENFLASHCARDS_SKIP_AUTH_ENABLED="${OPENFLASHCARDS_SKIP_AUTH_ENABLED:-true}"

envsubst \
  '${OPENFLASHCARDS_API_URL} ${OPENFLASHCARDS_API_TIMEOUT} ${OPENFLASHCARDS_API_RETRY_ATTEMPTS} ${OPENFLASHCARDS_API_RETRY_DELAY} ${OPENFLASHCARDS_SKIP_AUTH_ENABLED}' \
  < "$template_path" \
  > "$output_path"
